const R=[
{open:'Global Expansion',text:'Markets are calm, credit is available, and global demand is rising.',shock:'Federal Reserve Rate Hike',shockText:'The Fed unexpectedly raises rates by 2%. The dollar strengthens and global borrowing costs rise.',i:{invest:{w:8,l:-6,r:7,p:1,h:0},cash:{w:3,l:5,r:-4,p:0,h:0},borrow:{w:11,l:12,r:14,p:-2,h:0},hedge:{w:-2,l:-4,r:-8,p:1,h:25}},s:{invest:{w:-2,l:-1,r:3,p:0,h:0},cash:{w:2,l:1,r:-2,p:1,h:0},borrow:{w:-15,l:-5,r:8,p:-2,h:0},hedge:{w:8,l:0,r:-4,p:2,h:0}}},
{open:'Trade Friction',text:'Trade negotiations are deteriorating. Position before governments announce their response.',shock:'Global Trade War',shockText:'Major economies impose tariffs. Cross-border demand falls and supply chains become more expensive.',i:{invest:{w:7,l:-5,r:6,p:1,h:0},cash:{w:2,l:5,r:-3,p:0,h:0},borrow:{w:10,l:12,r:13,p:-2,h:0},hedge:{w:-2,l:-4,r:-7,p:1,h:25}},s:{invest:{w:-13,l:-4,r:6,p:-2,h:0},cash:{w:1,l:1,r:-1,p:1,h:0},borrow:{w:-17,l:-6,r:9,p:-3,h:0},hedge:{w:10,l:0,r:-5,p:3,h:0}}},
{open:'Emerging-Market Stress',text:'Capital is leaving emerging markets. Brazil promises to defend the real.',shock:'Brazilian Real Crisis',shockText:'The real depreciates 20%. Unhedged foreign-currency exposure produces immediate losses.',i:{invest:{w:7,l:-5,r:6,p:1,h:0},cash:{w:2,l:5,r:-3,p:0,h:0},borrow:{w:10,l:12,r:13,p:-2,h:0},hedge:{w:-2,l:-4,r:-7,p:1,h:25}},s:{invest:{w:-16,l:-5,r:8,p:-2,h:0},cash:{w:0,l:1,r:-1,p:0,h:0},borrow:{w:-14,l:-5,r:8,p:-3,h:0},hedge:{w:15,l:0,r:-6,p:3,h:0}}},
{open:'Energy Uncertainty',text:'Energy markets tighten while inflation expectations rise. Make the final allocation.',shock:'Commodity Price Shock',shockText:'Energy prices rise sharply. Inflation increases and operating margins tighten.',i:{invest:{w:8,l:-6,r:7,p:1,h:0},cash:{w:2,l:5,r:-3,p:0,h:0},borrow:{w:10,l:12,r:13,p:-2,h:0},hedge:{w:-2,l:-4,r:-7,p:1,h:25}},s:{invest:{w:-4,l:-3,r:5,p:0,h:0},cash:{w:-2,l:1,r:-1,p:0,h:0},borrow:{w:-16,l:-6,r:9,p:-3,h:0},hedge:{w:11,l:0,r:-5,p:3,h:0}}}
];
const C={'FIN-420':['Track FX exposure, liquidity, hedge coverage, and home-currency resilience.',['Where did exchange-rate exposure become visible?','When did hedge protection justify its immediate cost?','How did global rates affect financing flexibility?']], 'FIN-450':['Compare cumulative wealth with risk-adjusted survival and protection costs.',['Did the wealth leader take the best risk-adjusted path?','Which shock made protection most valuable?','How would position limits change the outcome?']], 'FIN-325':['Balance growth, liquidity, borrowing capacity, reputation, and resilience.',['When did liquidity become more valuable than growth?','How did borrowing change financial flexibility?','Which decision would be hardest to defend to a board?']], 'ECO-412':['Observe choices, switching, confidence, loss aversion, and possible herding.',['Did visible rankings create herding?','Which decision reflected loss aversion?','Where did confidence exceed available information?']]};
let S=JSON.parse(localStorage.getItem('gcr-v2'))||{round:0,resolved:false,course:'FIN-420',teams:[]};const $=x=>document.getElementById(x),cap=(x)=>Math.max(0,Math.min(100,x)),save=()=>localStorage.setItem('gcr-v2',JSON.stringify(S));
function surv(t){return Math.round(t.w*.45+t.l*.2+(100-t.r)*.2+t.p*.1+t.h*.05)}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c])}function sign(n){return `${n>0?'+':''}${n}`}function cls(n){return n>0?'up':n<0?'down':'flat'}
function apply(t,x){t.w=Math.round((t.w+x.w)*10)/10;t.l=cap(t.l+x.l);t.r=cap(t.r+x.r);t.p=cap(t.p+x.p);t.h=cap(t.h+x.h)}
function preview(t){if(!t.choice)return '';let x=R[S.round].i[t.choice];return `<div class="preview"><b>Immediate decision effect</b><div class="preview-grid"><span>Wealth ${sign(x.w)}</span><span>Liquidity ${sign(x.l)}</span><span>Risk ${sign(x.r)}</span><span>Rep. ${sign(x.p)}</span><span>Hedge ${sign(x.h)}</span></div></div>`}
function metric(label,val,d,suffix=''){let txt=d===undefined?'':`<span class="delta ${cls(d)}">${sign(d)} this step</span>`;return `<div class="metric"><span>${label}</span><strong>${val}${suffix}</strong>${txt}</div>`}
function teamCard(t,i){let d=t.last||{};let max=Math.max(...t.hist.map(h=>h.w),110);let bars=t.hist.map((h,j)=>`<div class="bar" style="height:${Math.max(6,h.w/max*45)}px"><em>R${j}</em></div>`).join('');return `<article class="team"><h3>${esc(t.name)}</h3><div class="meta"><span>${esc(t.region)}</span><span>${t.stage||'Opening position'}</span></div><div class="metrics">${metric('WEALTH','$'+t.w,d.w,'M')}${metric('LIQUIDITY',t.l,d.l)}${metric('RISK',t.r,d.r)}${metric('REPUTATION',t.p,d.p)}${metric('HEDGE',t.h,d.h,'%')}${metric('SURVIVAL',surv(t),d.s)}</div><div class="choices">${['invest','cash','borrow','hedge'].map(c=>`<button class="choice ${t.choice===c?'selected':''}" data-team="${i}" data-choice="${c}" ${S.resolved?'disabled':''}>${{invest:'Invest',cash:'Cash',borrow:'Borrow',hedge:'Hedge'}[c]}</button>`).join('')}</div>${preview(t)}<div class="history">${bars}</div><button class="remove" data-rm="${i}" ${S.resolved?'disabled':''}>Remove</button></article>`}
function render(){let r=R[Math.min(S.round,3)];$('course').value=S.course;$('brief').textContent=C[S.course][0];$('round').textContent=`${S.round+1} / 4`;$('count').textContent=S.teams.length;$('eventTitle').textContent=S.resolved?r.shock:`Round ${S.round+1}: ${r.open}`;$('eventText').textContent=S.resolved?r.shockText:r.text;$('status').textContent=S.resolved?'SHOCK REVEALED':'OPEN';$('impact').classList.toggle('hidden',!S.resolved);$('impact').innerHTML=S.resolved?'<b>Round outcome recorded.</b> Each team card now shows the shock-specific change and its cumulative path.':'';$('resolve').classList.toggle('hidden',S.resolved);$('next').classList.toggle('hidden',!S.resolved);$('next').textContent=S.round===3?'Show final debrief':'Advance to next round';$('resolve').disabled=!S.teams.length||S.teams.some(t=>!t.choice);$('submitted').textContent=`${S.teams.filter(t=>t.choice).length} of ${S.teams.length} decisions entered`;$('teams').innerHTML=S.teams.length?S.teams.map(teamCard).join(''):'<p class="muted">Add teams to begin.</p>';board();$('debrief').classList.toggle('hidden',!(S.resolved&&S.round===3));if(S.resolved&&S.round===3)debrief();save()}
function board(){let a=[...S.teams].sort((x,y)=>surv(y)-surv(x));$('board').innerHTML=a.length?a.map((t,i)=>`<tr><td>${i+1}</td><td><b>${esc(t.name)}</b></td><td>${esc(t.region)}</td><td>$${t.w}M</td><td>${t.l}</td><td>${t.r}</td><td>${t.p}</td><td>${t.h}%</td><td>${surv(t)}</td></tr>`).join(''):'<tr><td colspan="9" class="muted">No teams yet.</td></tr>'}
function debrief(){let by=f=>[...S.teams].sort(f)[0],a=[['Highest wealth',by((x,y)=>y.w-x.w)],['Lowest risk',by((x,y)=>x.r-y.r)],['Best survival',by((x,y)=>surv(y)-surv(x))],['Highest liquidity',by((x,y)=>y.l-x.l)]];$('awards').innerHTML=a.map(([l,t])=>`<div class="award"><span>${l}</span><strong>${esc(t.name)}</strong></div>`).join('');$('questions').innerHTML='<b>Debrief prompts</b><ol>'+C[S.course][1].map(q=>`<li>${q}</li>`).join('')+'</ol>'}
$('teamForm').onsubmit=e=>{e.preventDefault();let n=$('name').value.trim();if(!n)return;S.teams.push({name:n,region:$('region').value,w:100,l:50,r:50,p:50,h:0,choice:null,last:{},stage:'Opening position',hist:[{w:100}]});$('name').value='';render()};
$('teams').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.choice){let t=S.teams[+b.dataset.team];t.choice=b.dataset.choice;let before={...t};apply(t,R[S.round].i[t.choice]);t.last={w:R[S.round].i[t.choice].w,l:R[S.round].i[t.choice].l,r:R[S.round].i[t.choice].r,p:R[S.round].i[t.choice].p,h:R[S.round].i[t.choice].h,s:surv(t)-surv(before)};t.stage='After decision cost';render()}if(b.dataset.rm!==undefined){S.teams.splice(+b.dataset.rm,1);render()}};
$('resolve').onclick=()=>{let r=R[S.round];S.teams.forEach(t=>{let before={...t},x=r.s[t.choice];apply(t,x);t.last={w:x.w,l:x.l,r:x.r,p:x.p,h:x.h,s:surv(t)-surv(before)};t.stage='After global shock';t.hist.push({w:t.w});});S.resolved=true;render()};$('next').onclick=()=>{if(S.round<3){S.round++;S.resolved=false;S.teams.forEach(t=>{t.choice=null;t.last={};t.stage='Opening position'});render()}else $('debrief').scrollIntoView({behavior:'smooth'})};$('course').onchange=e=>{S.course=e.target.value;render()};$('reset').onclick=()=>{if(confirm('Erase this browser session?')){S={round:0,resolved:false,course:$('course').value,teams:[]};render()}};$('export').onclick=()=>{let rows=[['Team','Region','Wealth','Liquidity','Risk','Reputation','Hedge','Survival'],...S.teams.map(t=>[t.name,t.region,t.w,t.l,t.r,t.p,t.h,surv(t)])],csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='global-crisis-room-v2-results.csv';a.click()};render();